services:
  - type: web
    name: legal-rag-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: chmod +x .render-build.sh && ./.render-build.sh
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT --workers 1
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000  # Default port if $PORT not set (Render will override this)
      - key: VOYAGE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false