services:
  - type: web
    name: legal-rag-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000  # Fallback port (Render will override $PORT in production)
      - key: RENDER_HEALTH_CHECK_TIMEOUT_SECONDS
        value: "120"  # Extended timeout for RAG initialization
      - key: VOYAGE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false